apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: spire
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'kubernetes-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        
      - job_name: 'spire-infrastructure'
        metrics_path: '/'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:          
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: (spire-server|spire-agent)
          action: keep
          
        - source_labels: [__address__]
          regex: '.*:(8088|8089)'
          action: keep
          
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: application
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: instance
        
      - job_name: 'spring-actuator'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ['spire']
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_metrics]
          action: keep
          regex: "true"

        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: "9090"

        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: service